### ISSUE TITLE
hoe governanceType nu geregeld is, is niet uitbreidbaar

### ISSUE THREAD

**Issue by CHAOSdonut** [Logius-standaarden/respec#14]
governanceType word nu gemaakt door 1 10 en 100 tallen op te tellen bij een nummer en daar komt dan een nummer uit die gebruikt word in een switch om de juiste optie te kiezen.

dit systeem geeft alleen maar 9 opties per getal in de uiteindelijke getallenreeks.

het eerste getal is voor welke organisatie het is nu 1 voor geonovum en 2 voor logius.
in dit systeem is er dus maar ruimte voor 9 organisaties.

**Comment by CHAOSdonut** [comment]
Dit systeem mag op de schop, het gedeelte dat je keuze hebt tussen bedrijven kan weg omdat je alleen een document voor jou bedrijf maakt en dus de checks voor andere bedrijfsnamen overbodig is.

Het lijkt me het beste als een gebruiker een lijst van statussen kan maken die dan in het document gebruikt kunnen worden. zo voorkom je dat je voor ieder bedrijf checks van bedrijfsnaam + status in je switchcase moet zetten.

**Comment by sanderke** [comment]
>Verder is het misschien handig om de configuratie te splitsen in verschillende files.

Dit staat nu als apart issue in #21

**Comment by CHAOSdonut** [comment]
closed met: https://github.com/Logius-standaarden/respec/pull/17
