### ISSUE TITLE
Wikipagina's

### ISSUE THREAD

**Issue by sanderke** [Logius-standaarden/respec#32]
Wanneer er een config mist komt er netjes een waarschuwing met een link naar de wikipagina voor uitleg en voorbeeld. Nog niet alle pagina's bestaan.

- [ ] [localizationStrings](https://github.com/Logius-standaarden/respec/wiki/localizationStrings)
- [ ] [licenses](https://github.com/Logius-standaarden/respec/wiki/licenses)
- [x] [specStatus](https://github.com/Logius-standaarden/respec/wiki/specStatus)
- [x] [nl_organisationName](https://github.com/Logius-standaarden/respec/wiki/nl_organisationName)
- [x] [governanceTypeText](https://github.com/Logius-standaarden/respec/wiki/governanceTypeText)
- [x] [govTextCode](https://github.com/Logius-standaarden/respec/wiki/govTextCode)
- [x] [sotdText](https://github.com/Logius-standaarden/respec/wiki/sotdText)

**Comment by CHAOSdonut** [comment]
localizationStrings en licenses zijn toegevoegd aan de wiki
