### ISSUE TITLE
list of todos

### ISSUE THREAD

**Issue by RickdeBruijn** [Logius-standaarden/respec#36]
## profiles/logius.js: ##
- [x] logius/fix-md-elements.js: check
- [x] w3c/level.js: check if this must be skipped
- [x] w3c/group.js: check if this must be skipped

### fix-md-elements.js ###
- [x] check if algorithm is correct!
- [x]  do nothing if this config is not set?

### headers.js ###
- [x] strip w3c specific content
- [x] document license types for Geonovum
- [x] check fixed, static urls
- [x] no clear 'ED' status in this version
- [x] check path generation
- [x] #41 
- [x] add an extra check, because now it seems that showPreviousVersion is true in (too) many cases?
- [x] check GN STATUSES in templates
- [x] check if logius will still use
- [x] Pieter: do we need these?
- [x] Pieter: is the comment below valid in this version?
- [x] Pieter valid?
- [x] pieter commented out
- [x] revert geonvum alterations

### splitmarkdownheaders.js ###
- [ ] refactor + correct commenting etc
- [ ] testing
- [ ] Todo

### dfn-panel.css.js ###
- [x] Revert changes due to https://github.com/w3c/respec/pull/2888 when https://github.com/w3c/css-validator/pull/111 is fixed.

## tests/test-main.js ##
- [x] Remove this when browsers add support for top level await

## test/testindexStable.html ##
- [x] when <dialog> becomes a implemented, we should really use that.

**Comment by CHAOSdonut** [comment]
#38 
if-statement opgeschoond en gekeken of de functie werkt

**Comment by CHAOSdonut** [comment]
#39 
W3C/level & W3C/group zijn functionaliteiten van W3C, ik verwacht niet dat gebruikers van dit profiel het vaak nodig zullen hebben maar het verwijderen van de functionaliteit heeft geen meerwaarden.

**Comment by CHAOSdonut** [comment]
### tests/test-main.js
Remove this when browsers add support for top level await
alle moderne versies van browsers (behalve IE) supporten top level await: https://caniuse.com/?search=top%20level%20await

deze todo komt van W3C dus ik laat hem wel staan

**Comment by CHAOSdonut** [comment]
todos die bij W3C vandaan komen moeten blijven staan. Als we ze toch willen sluiten is het beter om een pull request in te dienen bij W3C

**Comment by CHAOSdonut** [comment]
### test/testindexStable.html
when `<dialog>` becomes a implemented, we should really use that.

**Comment by sanderke** [comment]
> todos die bij W3C vandaan komen moeten blijven staan. Als we ze toch willen sluiten is het beter om een pull request in te dienen bij W3C

Als het in het Logius-profiel staat komt het waarschijnlijk doordat begonnen is met een kopie van een W3C-bestand en zijn die todo's irrelevant en te verwijderen uit de kopie.

**Comment by CHAOSdonut** [comment]
> > todos die bij W3C vandaan komen moeten blijven staan. Als we ze toch willen sluiten is het beter om een pull request in te dienen bij W3C
> 
> Als het in het Logius-profiel staat komt het waarschijnlijk doordat begonnen is met een kopie van een W3C-bestand en zijn die todo's irrelevant en te verwijderen uit de kopie.

Ook als de todos ook bij de huidige versie van W3C nog aanwezig zijn?
