### ISSUE TITLE
Organisatielogo heel klein getoond

### ISSUE THREAD

**Issue by lvdbrink** [Logius-standaarden/respec#49]
## Description of problem
Het organisatielogo van Geonovum wordt heel klein getoond. Wordt een bepaalde afmeting verwacht? 

Ik heb het als volgt geconfigureerd, met zelfde height en width als andere geonovum respec documenten: 

<pre>
logos: [{
    src: "https://tools.geostandaarden.nl/respec/style/logos/Geonovum.svg",
    alt: "Geonovum",
    id: "Geonovum",
    height: 67,
    width: 132,
    url: "https://www.geonovum.nl/geo-standaarden",
  }],
</pre>

**URL to affected spec or repo:**

[https://github.com/lvdbrink/logius-respec-test/](https://github.com/lvdbrink/logius-respec-test/)

**Expected behavior (e.g., it shouldn't crash):**
Het zou getoond moeten worden zoals bv in [dit document](https://docs.geostandaarden.nl/g4w/geox/)

**Comment by CHAOSdonut** [comment]
ik heb beide documenten geopend en ze zijn dezelfde grootte bij mij:
<img width="960" alt="vb1" src="https://user-images.githubusercontent.com/48866583/212914695-f1e3f82b-325d-4c14-b37c-6b096619870e.PNG">
<img width="960" alt="vb2" src="https://user-images.githubusercontent.com/48866583/212914757-45f20ded-a9cd-42a4-a3cf-d56b3019d3fb.PNG">

mis ik iets of werkt het al?

**Comment by lvdbrink** [comment]
Ik kan het ook niet meer reproduceren. Iets met height/width niet meteen goed instellen in combinatie met cache ofzo...
