### ISSUE TITLE
Fout in gegenereerde URL

### ISSUE THREAD

**Issue by lvdbrink** [Logius-standaarden/respec#51]
## Description of problem
Logius-Respec zet in de URL van "**Vorige versie**" en "**Deze versie**" (bij 'specStatus=DEF')", dwz in de persistente URI, de `shortName` neer als folder in het pad, terwijl deze alleen in de bestandsnaam hoort te staan.

**URL to affected spec or repo:**

https://lvdbrink.github.io/logius-respec-test/

**What happened (e.g., it crashed)?:**
Met deze parameters: 

<pre>
organisation-config.js: 

 nl_organisationPublishURL: "https://docs.geostandaarden.nl/",
 
config.js: 

  specStatus: "DEF",
  specType: "HR",
  pubDomain: "lvdbrink",
  shortName: "lindatest",
  publishDate: "2023-03-30",
  previousPublishDate: "2023-02-20",
  previousMaturity: "VV",
</pre>

Deze URLs werden gegenereerd: 

> Deze versie: https://docs.geostandaarden.nl/lvdbrink/lindatest/def-hr-lindatest-20230330/

> Vorige versie: https://docs.geostandaarden.nl/lvdbrink/lindatest/vv-hr-lindatest-20230220/

**Expected behavior:**
> Deze versie: https://docs.geostandaarden.nl/lvdbrink/def-hr-lindatest-20230330/

> Vorige versie: https://docs.geostandaarden.nl/lvdbrink/vv-hr-lindatest-20230220/

NB de shortName staat WEL correct in de laatst gepubliceerde versie.

**Comment by sanderke** [comment]
De URL is nu aan te passen. Het onderstaande voorbeeld zou het gewenste gedrag moeten nabootsen.

```js
edDraftURI: ["github"],
latestVersion: ["nl_organisationPublishURL", "pubDomain", "/"],
thisVersion: ["nl_organisationPublishURL", "pubDomain", "/", "specStatus", "-", "specType", "-", "shortName", "-", "publishDate"],
prevVersion: ["nl_organisationPublishURL", "pubDomain", "/", "previousMaturity", "-", "specType", "-", "shortName", "-", "publishDate"],
```

Het resultaat is in de [template](https://logius-standaarden.github.io/ReSpec-template/) te bekijken.
