### ISSUE TITLE
Content Security Policy (CSP) guidance

### ISSUE THREAD

**Issue by janvlug** [Logius-standaarden/respec#54]
I would like to enable a Content Security Policy (CSP) header at my server that provides ReSpec documentation.

I would like to have guidance for the needed CSP header.

Currently, I use a CSP header like:
```
Content-Security-Policy "default-src 'self'; object-src 'none';
script-src 'self' 
https://cdn.jsdelivr.net https://gitdocumentatie.logius.nl https://www.w3.org/
'unsafe-eval'
'sha256-IqEw5dW9/Oy9ROOY62J4mpgayYHKKEpfm8oqtT47pAI='
'sha256-nmDrrNE1w3TeOvAPnX4VnK0KuCY2OK994B3pl0t0hxM='
'sha256-dj1DTzlsfX1B7F/gWZpEdb9OOM5Z+oXaYRf7uAnfUbs='
'sha256-MJtSOWoY3m7El25Dw9gIBXLaar2UySjZiOsVPDEbX2A='
'sha256-RlvzB5Qdozexpa6ScOHQWHJ8KaIBfAp1Cg31WbSnHk8='
'sha256-ir5Gs/gWwBRRT3vDxGHExBe1SFMOVtH2P3wGEL5xEf0=';
img-src 'self'
https://gitdocumentatie.logius.nl;
frame-src 'none'; frame-ancestors 'none'
style-src 'self'
'unsafe-hashes'
'sha256-KxT1NePqSxwBHfNDgKlL+OckNFUTOcKMj8ymz/EfvrY='
'sha256-TKEPDnFBh4RGp9B4KXfy/CT/SKRtUypJ2FR9BJfDCYI='
'sha256-9oKyfH/t541MkfU6J1GyCF+r27k+28HmP1bFEjAfNh4='
'sha256-dj1DTzlsfX1B7F/gWZpEdb9OOM5Z+oXaYRf7uAnfUbs='
'sha256-hwBsoQ+EihBT3kcmrEH+XurjswJ9fOBRHv5gZReP1cA='
'sha256-MJtSOWoY3m7El25Dw9gIBXLaar2UySjZiOsVPDEbX2A=';
worker-src 'self' blob:"
```

(Note: the above might be not totally correct, as I manually tried to minimize the header for clarity)

What I especially am a bit worried about is:
- `script-src 'unsafe-eval'`
- `style-src 'unsafe-hashes'`
- `worker-src blob:`

Note that we host also non-ReSpec on the same domain.

We can do tests with CSP headers if that would be helpful.

See for more info also [this article](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html).

**Comment by janvlug** [comment]
You can run a test at internet.nl for a security scan. This site states in the scan results "We test for the settings below that are the fundament of a secure CSP configuration.". After this are descriptions of detailed settings for the CSP header.

This is as an example the result for the CSP headers for https://logius-standaarden.github.io/ReSpec-template/:

https://internet.nl/site/logius-standaarden.github.io/1983775/#control-panel-29

The above mentioned site site also contains a reference to [Web application guidelines from NCSC-NL](https://www.ncsc.nl/documenten/publicaties/2019/mei/01/ict-beveiligingsrichtlijnen-voor-webapplicaties).

**Comment by sanderke** [comment]
We advise to publish static snapshots to reduce the dependency on JS, e.g.:
https://gitdocumentatie.logius.nl/publicatie/api/adr/

It appears our publication server has a [100% score](https://internet.nl/site/gitdocumentatie.logius.nl/1991912/#control-panel-29), but still lacks the recommended CSP settings.

**Comment by janvlug** [comment]
Thanks for the advise @sanderke. I will test the CSP requirements when I use [static snapshots](https://respec.org/docs/#static-snapshots).

**Comment by janvlug** [comment]
With static snapshots things work way better. But there are inline <style>-elements which need their sha256 hash added to the Content-Security-Policy header.

However inline styles like this one
```
<img style="float: left; padding-right: 5px;" src="https://tools.geostandaarden.nl/respec/style/logos/cc-by.svg" alt="Logo Creative Commons Attribution 4.0 International Public License">
```
cannot be allowed by using a sha256 hash (see [this](https://stackoverflow.com/questions/63934589/csp-header-fails-with-refused-to-apply-inline-style-but-i-have-already-adde)).

Ideally styles should be in a style document.

**Comment by janvlug** [comment]
See here the result of the lost styling around the image of the license:
https://standaarden.overheid.nl/tooi/doc/tooi-thesauri/

**Comment by sanderke** [comment]
> Ideally styles should be in a style document.

Thank you. The style has been moved to a seperate `<style>` block. This change is live now in version 34.1.4.
