### ISSUE TITLE
Date in URI incorrectly formatted

### ISSUE THREAD

**Issue by lvdbrink** [Logius-standaarden/respec#56]
## Description of problem

- The dates in URIs generated by ReSpec (This version, previous version) are incorrectly formatted. 
- One day is subtracted from the configured date.

**URL to affected spec or repo:**

https://github.com/lvdbrink/logius-respec-test/

(At the moment the header is not shown, see [other bug](https://github.com/Logius-standaarden/respec/issues/55).)

**What happened (e.g., it crashed)?:**

With config: `  publishDate: "2023-03-15",`

The date in permalinks is formatted like this `03/14/2023/`

The date is  e.g. 14th of March, when it should be 15th as configured.

This happens both in "This version" URLs and "Previous version" URLs.

**Expected behavior (e.g., it shouldn't crash):**

The date as generated in the URL should be `20230315`

Correct example: https://docs.geostandaarden.nl/g4w/geox/

**Optional, steps to reproduce:**

1.  ...

**Comment by sanderke** [comment]
The slashes should already be fixed, like in [this example](https://sanderke.github.io/logius-respec-test-GN/).

An old feature was recovered that would change the date in the subtitle to the date the document was last edited if
```js
specStatus == "WV"
```
This has been removed in b0c884a4386ab5fbf18abd00367549fbbd084954 in this generic profile. A new build will be available from midnight.

**Comment by lvdbrink** [comment]
Weird things with dates are still happening. 

See https://lvdbrink.github.io/logius-respec-test/

The slashes are fixed; but 1 day is still being deducted from the configured date. 

**This version** as shown in my browser: `https://docs.geostandaarden.nl/lvdbrink/wv-hr-lindatest-20230329` (when publishDate is 30th of March)

**Previous version** is now even weirder: `[ttps://docs.geostandaarden.nl/lvdbrink/vv-hr-lindatest-mon feb 20 2023 00:00:00 gmt+0100 (central european standard time`

**Comment by sanderke** [comment]
I could recreate the issue of the date offset when viewing in Edge. Merging https://github.com/w3c/respec/pull/4385 seems to have solved it. Probably a time zone mishap.
The previous publish date was an oversight, corrected in https://github.com/Logius-standaarden/respec/commit/87432d9a588835406bcbc3adaf0ba4fbf06fdeeb .

Build coming.

**Comment by sanderke** [comment]
Resolved with new build.
