### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by mvb-nerdzone** [Logius-standaarden/respec#57]
**Is your feature request related to a problem? Please describe.**
I've been looking for a couple of days why my ReSpec-projects based on the [Logius ReSpec-Template](/Logius-standaarden/respec-template) were not working anymore. I thought it was because of changes I made but it appears that there must have been some changes in depended code as described in the closed isssue #55 (I had the same issue).

**Describe the solution you'd like**
* Some kind of changelog, where at least breaking changes are described.
* Some kind of notification-process to announce breaking changes.

**Additional context**
N/A

**Describe any alternatives you've considered**
N/A

**Comment by sanderke** [comment]
Warnings should have been added. Apologies for the inconvenience.

**Comment by sanderke** [comment]
Release notes will be placed here: https://github.com/Logius-standaarden/respec/releases
No breaking change in latest release.
