### ISSUE TITLE
'previousVersion' in 'config.js' vervangen door previousPublishVersion'?

### ISSUE THREAD

**Issue by melsk-r** [Logius-standaarden/respec#61]
In de ['config.js' van het Logius Respec template](https://github.com/Logius-standaarden/ReSpec-template/blob/main/js/config.js) kom ik de property 'previousVersion' tegen. Die property wordt echter nergens beschreven, niet in het side menu van de [Logius Respec wiki](https://github.com/Logius-standaarden/respec/wiki/Developers-Guide) en ook niet in de side menu van de [W3C Respec wiki](https://github.com/w3c/respec/wiki/).
Wel kom ik 'previousPublishVersion' tegen. Moet 'previousVersion' in de 'config.js' niet vervangen worden door 'previousPublishVersion'?

**Comment by sanderke** [comment]
Bedankt. Het moet inderdaad `previousPublishVersion` zijn.
