### ISSUE TITLE
Wat is het voordeel van het gebruik van de 'content' configuratie property

### ISSUE THREAD

**Issue by melsk-r** [Logius-standaarden/respec#68]
Je kunt grofweg op 2 manieren de inhoud van Respec documentatie assembleren:
* door in de index.html 'section' elementen op te nemen;
* door gebruik te maken van de 'content' configuratie property.

Ik vraag me alleen af waarom ik überhaupt gebruik zou maken van die laatste optie. Wat is daarvan het voordeel t.o.v. de eerste optie?

**Comment by sanderke** [comment]
De tweede optie is een product uit een stageopdracht. Het verzoek was schrijvers een optie te geven enkel de configuratie in `config.js` bij te hoeven werken. Hierdoor is ook de titel aan te passen buiten `index.html` om.

Zelf blijf ik bij de eerste optie; Scheelt weer een scriptje en geeft meer opties.
