### ISSUE TITLE
Foutieve generatie en diverse build errors/warnings

### ISSUE THREAD

**Issue by melsk-r** [Logius-standaarden/respec#70]
Bij het genereren van de Respec documentatie treden er ineens errors op waar dat 2 maanden geleden nog niet het geval was en mis ik de header van het document.

URL to affected spec or repo: 
* https://github.com/VNG-Realisatie/MBG-Werkomgeving
* https://vng-realisatie.github.io/MBG-Werkomgeving/

Als je de laatste url opent dan zie je dat de header van het Respec document nu ontbreekt terwijl die in [de versie van dit document die ik begin maart heb gegenereerd](https://vng-realisatie.github.io/publicatie/cim/mbg/0.9.0/) nog wel aanwezig was.

In het [build report](https://github.com/VNG-Realisatie/MBG-Werkomgeving/actions/runs/9093694522/job/24993183731) zie je bij Static HTML dat er een undefined error optreedt.

Zoals je in de [build en check report](https://github.com/VNG-Realisatie/MBG-Werkomgeving/actions/runs/9093694522) kunt zien wordt er trouwens ook een waarschuwing op het gebruik van node.js 16 gegeven.

**Comment by sanderke** [comment]
Error: `TypeError: Cannot read properties of undefined (reading 'st')`

De bug zit in de organisation-config.js. Hier is `st` uitgecommentarieerd terwijl dit nog wel als `specType` in config.js staat.
https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/commit/f5fd558d5871bed334a50a5bf64498664a880305
