### ISSUE TITLE
Unexpected peertube warning

### ISSUE THREAD

**Issue by janvlug** [Logius-standaarden/respec#71]
## Description of problem

I see this ReSpec warning in Firefox 127.0, but not in Chromium:

```
Found linkless <a> element with text "Watch on PeerTube" but no matching <dfn>

Occurred 1 times at:

<a>(http://localhost:8000/#ptc-notification-watch) element

(plugin: "core/link-to-dfn")
```

![image](https://github.com/Logius-standaarden/respec/assets/5903208/c296b71a-f513-47aa-b83c-11e17c0d4dac)

**Comment by sanderke** [comment]
Do you still have this discrepancy after a hard refresh in both browsers?
Is it possible to share the document?

**Comment by janvlug** [comment]
Thanks. I tried again in a new private Firefox window, and indeed, I do not see the message there. So it must be something lingering in Firefox. Closing this issue.

**Comment by janvlug** [comment]
The issue was caused by the [PeerTube Companion plugin](https://codeberg.org/Booteille/peertube-companion).
