### ISSUE TITLE
Vraag: Is paragraafnummering op meer niveaus dan de 3 hoogste mogelijk?

### ISSUE THREAD

**Issue by melsk-r** [Logius-standaarden/respec#75]
Op dit moment krijgen alleen de titels van de eerste 3 paragraaf niveau's een paragraafnummer.
Hoe kan ik ook voor de titel op het vierde niveau een paragraafnummer laten genereren?

**Comment by sanderke** [comment]
Je kan `maxTocLevel` uit de config verhogen of zelfs verwijderen als je geen limit wilt.

**Comment by melsk-r** [comment]
Daarmee configureer je toch hoeveel niveau's je wil opnemen in de Inhoudsopgave, toch niet hoeveel paragraaf niveau's in de inhoud van het document je een nummer wil laten hebben?

**Comment by sanderke** [comment]
Tot één niveau dieper dan de paragrafen in de ToC wordt genummerd.
Eenzelfde document met `maxTocLevel` resp. 2 en 3:

2. https://logius-standaarden.github.io/Digikoppeling-Koppelvlakstandaard-WUS/?maxTocLevel=2#point-to-point-beveiliging
3. https://logius-standaarden.github.io/Digikoppeling-Koppelvlakstandaard-WUS/?maxTocLevel=3#point-to-point-beveiliging

**Comment by melsk-r** [comment]
Ah, dat maakt het duidelijker. Vind ik aan de ene kant wel netjes aan de andere kant bestaat dan het gevaar dat de Toc erg lang wordt. Is er een reden waarom jullie dit indertijd zo hebben ingeregeld? Of was dit al zo ingeregeld in de Respec JS library dat jullie gebruiken?

**Comment by sanderke** [comment]
Dit wordt geregeld in een "core" module van W3C (`src/core/structure.js`).

**Comment by melsk-r** [comment]
Duidelijk, dan zal BZK het daarmee moeten doen. Dank je.
